### ISSUE TITLE
Description and Tests are looking for different solutions

### ISSUE THREAD

**Issue by f-mac** [rmotr-curriculum/base-python-curriculum#28]
**Week 1 - Quiz --> All in String**

The description asks for the count of words in a string, while the assert tests use characters in a string. First chunk of code is what should be the solution while the latter bit is what's needed to pass the tests.

Correct code for description:
```
def all_in_string(a_string, s1, s2, s3):
    count = 0
    for word in a_string.split():
        if word in (s1,s2,s3):
            count += 1 
    return count
```

Code to pass tests:
```
def all_in_string(a_string, s1, s2, s3):
    count = 0
    for c in a_string:
        if c in (s1,s2,s3):
            count += 1 
    return count
```

**Comment by santiagobasulto** [comment]
@f-mac I think you're approaching this problem in the other direction. Instead of splitting the original string and checking which parts of the original strings are in the words that you receive, I'd do it the other way. **I'd check which words are part of the large string**. Example:

```python
count = 0
for word in [s1, s2, s3]:
    if word in a_string:
        count += 1
return count
```

Makes sense?

PS: I'm using a list, the assignment's solution makes it a little bit more clear: https://github.com/rmotr-curriculum/base-python-curriculum/blob/master/unit-17-week-1-quiz/lesson-3-all-in-string/solutions/solution_.py

**Comment by f-mac** [comment]
totally makes sense. thanks santiago
